# application.yml - SOLO PRODUCCIÓN CON POSTGRESQL
spring:
  application:
    name: devpath-backend

  # POSTGRESQL EN PRODUCCIÓN - CONFIGURACIÓN SEPARADA
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    com.devpath: INFO
    root: INFO
