# application.yml - PERFECTO PARA AMBOS ENTORNOS
spring:
  application:
    name: devpath-backend

  # DESARROLLO LOCAL (default profile)
  datasource:
    url: jdbc:h2:mem:devpathdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # Para Docker

jwt:
  secret: "ZGV2cGF0aC1zZWNyZXQta2V5LTIwMjQtbXV5LXNlZ3VyYS1wYXJhLWRlc2Fycm9sbG8="
  expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.devpath: DEBUG
    org.springframework.security: DEBUG

---
# PRODUCCIÓN (perfil prod) - TAMBIÉN H2
spring:
  config:
    activate:
      on-profile: prod
      
  # MISMA BD H2 PARA SIMPLICIDAD
  datasource:
    url: jdbc:h2:mem:devpathdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    
  h2:
    console:
      enabled: false  # Deshabilitado por seguridad

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api  # SIN /api en producción

logging:
  level:
    com.devpath: INFO
    root: INFO
