# application.yml - PERFECTO PARA AMBOS ENTORNOS
spring:
  application:
    name: devpath-backend

  # DESARROLLO LOCAL (default profile)
  datasource:
    url: jdbc:h2:mem:devpathdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: "ZGV2cGF0aC1zZWNyZXQta2V5LTIwMjQtbXV5LXNlZ3VyYS1wYXJhLWRlc2Fycm9sbG8="
  expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /api  # CAMBIO: quitar en producción

logging:
  level:
    com.devpath: DEBUG
    org.springframework.security: DEBUG

---
# PRODUCCIÓN (perfil prod)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}  
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: false

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /  # SIN /api en producción

logging:
  level:
    com.devpath: INFO
    root: INFO
